import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { ReactNode } from "react";
import Footer from "@/components/footer";
import { UserProvider } from "@/utils/userContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <Header />
          <div className="min-h-[calc(100vh-216px)]">{children}</div>
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
